channels:
- conda-forge
dependencies:
# Jupyter
- jupyterlab=3.29
- jupyter-offlinenotebook=0.2
- nodejs=12
- nbconvert=7.2
# RTC
- jupyterlab-link-share=0.2
# Python Kernel
- ipykernel=6.21
- xeus-python=0.15
- ipywidgets=8.0
- widgetsnbextension=4.0
- python=3.10